### ISSUE TITLE
Cancer cell fraction > 1.0

### ISSUE THREAD

**Issue by wschen** [FunGeST/Palimpsest#2]
I have generated clonality plots using the cnaCCF_plots() function and noticed that the cancer cell fraction histogram tends to show that values lie within the range of [0, 1.5]. This is also true for the plot on page 14 of the vignette included in the package. It seems strange for CCF to be >1.0 since the fraction of all tumor cells harboring a mutation can't be >100%, so I am wondering whether this is a result of a bug in the code or whether there is a different way to interpret CCF.

Thanks!
<img width="757" alt="screen shot 2018-06-15 at 3 04 17 pm" src="https://user-images.githubusercontent.com/7905491/41491348-76c00b74-70ad-11e8-830a-338198fdb135.png">

**Comment by northerngasc** [comment]
Thank you for your message.
Indeed a CCF >1 has no biological meaning.
The CCF reported by Palimpsest is directly the result of the VAF corrected for copy-number and tumor cell content. So due to random sampling of sequenced reads the clonal mutations will typically appear as a peak centered on 1, corresponding to the VAF peak around 0.5.
A CCF >1 should thus be interpreted as =1.
I hope it helps!
Eric
