### ISSUE TITLE
Error in getting DSB

### ISSUE THREAD

**Issue by beginner984** [FunGeST/Palimpsest#45]
Hello

I have used vcd_annotate function successfully but for DSB I get this error

```
DBS_input <- palimpsest_input(vcf = vcf, Type = "DBS")
Error in if (res$DBS_cat[i] == res$DBS_cat[i - 1] & res$Sample[i] == res$Sample[i -  : 
  missing value where TRUE/FALSE needed
```
I could not find the reason in google search
Please you may help?

Thanks

**Comment by benedict909** [comment]
Hello,

Thanks for getting in touch and sorry for not getting back to you sooner.

This error is likely caused by Palimpsest not being able to find any DBS mutations in your vcf. I would suggest you check that the VCF has been correctly ordered by Sample>CHROM>POS, as `palimpsest_input` needs these to be in the right order for DBS mutations to be counted. 

If you are still having this problem I would be happy to take a look at some of your example data.

Best wishes,
Benedict
